import AppThemeProvider from "@/theme/theme-provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body style={{ minHeight: "100vh" }}>
        <AppThemeProvider>{children}</AppThemeProvider>
      </body>
    </html>
  );
}
